export const SELECT_PRODUCT = "SELECT_PRODUCT";
export const UNSELECT_PRODUCT = "UNSELECT_PRODUCT";
export const LOAD_PRODUCT_LIST = "LOAD_PRODUCT_LIST";
export const PRODUCT_CHANGE = "PRODUCT_CHANGE";
