micronaut:
  application:
    name: server
---
#tag::cors[]
micronaut:
  server:
    cors:
      enabled: true
#end::cors[]
---
#tag::staticResources[]
micronaut:
  router:
    static-resources:
      default:
        enabled: true   #<1>
        mapping: "/**"  #<2>
        paths: "classpath:public" #<3>
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
#end::staticResources[]

datasources:
  default:
    url: ${JDBC_URL:`jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
    username: ${JDBC_USER:sa}
    password: ${JDBC_PASSWORD:""}
    driverClassName: ${JDBC_DRIVER:org.h2.Driver}
jpa:
  default:
    packages-to-scan:
      - au.id.kang.cheese.domain
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
